# Generated by Django 5.2.15 on 2026-06-16 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Persona',
        ),
        migrations.AlterModelOptions(
            name='dialog',
            options={'ordering': ['-last_message_at'], 'verbose_name': 'Dialog', 'verbose_name_plural': 'Dialogs'},
        ),
        migrations.AlterModelOptions(
            name='fan',
            options={'verbose_name': 'Fan', 'verbose_name_plural': 'Fans'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RenameField(
            model_name='dialog',
            old_name='model',
            new_name='persona',
        ),
        migrations.AlterUniqueTogether(
            name='dialog',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='unread_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fan',
            name='internal_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('fan', 'Fan'), ('chatter', 'Chatter')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('chatter', 'Chatter'), ('teamlead', 'Teamlead')], db_index=True, default='chatter', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='dialog',
            constraint=models.UniqueConstraint(fields=('persona', 'fan'), name='unique_persona_fan_dialog'),
        ),
        migrations.AlterModelTable(
            name='persona',
            table='crm_model',
        ),
    ]
